context:
  name: ministream
  version: "0.99.1"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: "https://gitlab.gnome.org/GNOME/${{ name }}/-/archive/${{ version }}/${{ name }}-${{ version }}.tar.gz"
  sha256: 4cd263f5b8c1e7c56a461b00fecfedc84e1eb5911ec7bf8749a76fdee5792192

build:
  number: 0
  script:
    - if: win
      then: |
        meson setup %MESON_ARGS% ^
          --prefix=%LIBRARY_PREFIX% ^
          --default-library=shared ^
          --wrap-mode=nofallback ^
          -Dintrospection=enabled ^
          -Dtests=false ^
          builddir
        ninja -v -C builddir -j %CPU_COUNT%
        ninja -C builddir install -j %CPU_COUNT%
      else: |
        meson setup ${MESON_ARGS} \
            --prefix=$PREFIX \
            --default-library=shared \
            --wrap-mode=nofallback \
            -Dintrospection=enabled \
            -Dtests=false \
            builddir
        ninja -v -C builddir -j ${CPU_COUNT}
        ninja -C builddir install -j ${CPU_COUNT}

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - meson
    - ninja
    - pkg-config
    - gobject-introspection
    - glib
  host:
    - glib
    - gobject-introspection
    - zlib
  run_exports:
    # Conservative ABI compatibility, may be able to be relaxed after the 1.0.0 release
    - ${{ pin_subpackage('ministream', upper_bound='x.x.x') }}

tests:
  - package_contents:
      files:
        - if: unix
          then: lib/pkgconfig/ministream.pc
        - if: win
          then: Library/lib/pkgconfig/ministream.pc
      lib:
        # rattler-build doesn't detect DLLs in a <name>-<so>.dll format
        - if: unix
          then: ministream
        - if: win
          then:
            - ministream.lib
            - ministream-*.dll

about:
  homepage: https://gitlab.gnome.org/GNOME/ministream
  summary: 'Minimal (subset) appstream metadata parser'
  description: |
    Provides a subset of AppStream support for building libraries like libadwaita
  license: LGPL-2.1-or-later
  license_file: COPYING
  repository: https://gitlab.gnome.org/GNOME/ministream

extra:
  recipe-maintainers:
    - danyeaw
